### PR TITLE
Correctly return the key value relationship and use this in IndexedRelationship

### PR DESCRIPTION
**Pull request by brycenz**
One of the reasons for changing the SortedTree.addNode to return the key value relationship was so that IndexedRelationship could use this as it was not guaranteed to always get the correct relationship.  However I forgot to change that one piece of code to use the returned relationship.

On changing that I found that the wrong relationship was being returned from addNode anyway (the key entry relationship rather than the key value relationship).  Have made changes to return the correct relationship.

Not sure of the policy on .gitignore files but I added one to ignore the target directory.

### CODE REVIEW

**Comment by peterneubauer** [comment]
@NielsHoogeveen do you want to check and merge?

**Comment by NielsHoogeveen** [comment]
I would like to merge the request, but github says: This pull request cannot be automatically merged.

**Comment by brycenz** [comment]
There have been other changes committed to the repo after this pull request was put in.  I am presently working on some larger changes to IndexedRelationship etc. based around extracting out a NodeCollection interface which then can be used as a backing data structure for the IndexedRelationship.  This makes IndexedRelationship independent from SortedTree, you could instead use a list, map, or any other exotic data structure you want to base the indexing on.

Getting close to having that done, so could possibly close this pull request, then get my current fork updated and issue new pull request once the current work is done.

However there are some changes in the new work I am doing that I wanted to discuss once I had them committed to my github fork before issuing pull request.

**Comment by NielsHoogeveen** [comment]
Looking forward to your changes. I am really glad you take such a serious interest in this component. This is how communities should work.

Let's discuss your changes once you have finished them,

**Comment by brycenz** [comment]
I have updated this pull request with my recent UnrolledLinkedList work, as well as the NodeCollection interface. @NielsHoogeveen since I think it has the most impact on your SortedTree code it would be good if you could decide if this fits in with that?

**Pull request merged**
